name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # commit_comment:
   # branches: [ "main" ]
  
   # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: vote
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
